project:
     type: book
     output-dir: docs

book:
     title: "Numerical Solutions of Differential Equations"
     author: "Waleed A A Ali"
     chapters:
          - index.qmd
          - 01_Internal.qmd
          - part: Part_LinAlg.qmd
            chapters:
               - 02_LinAlg.qmd
          - part: Part_IVPs.qmd
            chapters:
               - 03_IVP_Euler.qmd
               - 04_IVP_ModEuler.qmd
               - 05_IVP_RK4.qmd
               - 06_IVP_InBuilt.qmd
               - 07_IVP_Implicit.qmd
          - part: Part_BVPs.qmd
            chapters:
               - 08_BVP.qmd
               - 09_MVP.qmd
               - 10_SBVP.qmd
          - part: Part_PDEs.qmd
            chapters:
               - 11_PDE.qmd
     appendices:
          - Z_App_Basic.qmd
          - Z_App_Arrays.qmd
          - Z_App_Loops.qmd
          - Z_App_Plot.qmd
          - Z_App_ReadWrite.qmd
          - Z_App_GE.qmd
          - Z_App_MatDeco.qmd
          - Z_App_DataFit.qmd
          - Z_App_Eigen.qmd
          - Z_App_Root.qmd
     downloads: [pdf,docx,epub]

format:
     html:
          theme:
               light: [flatly,styleL.scss]
               dark: [darkly,styleD.scss]
          respect-user-color-scheme: true
          mainfont: Computer Modern Roman
          fontsize: 1rem
          page-layout: full
          code-link: true
          footnotes-hover: true
          code-line-numbers: true
     pdf:
          toc: true
          documentclass: scrreport
          papersize: a4
          code-line-numbers: true
          pdf-engine: pdflatex
     docx:
          toc: true
     epub: default